# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# Python
## pyenv & pyenv-virtualenv
# export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init --path)"
# eval "$(pyenv virtualenv-init -)"
